name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    - name: Install wget
      run: |
        pip install wget
        pip show wget
      env:
        ZLIB_PATH: Default

    - name: Install zlib
      run: |
        python -m wget https://downloads.sourceforge.net/project/gnuwin32/zlib/1.2.3/zlib-1.2.3-bin.zip -o zlib-1.2.3.zip
        unzip zlib-1.2.3.zip

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.1.0
      with:
        # Directory to install Qt
        #dir: # optional
        # Version of Qt to install
        version: 5.12.6 # optional, default is 5.12.6
        # Host platform
        #host: windows # optional
        # Target platform for build
        target: desktop # optional, default is desktop
        # Architecture for Windows/Android
        arch: win32_mingw73 # optional
        # Whether or not to install Qt dependencies on Linux
        #install-deps: true # optional, default is true

    - uses: actions/checkout@v1

    - name: List directory
      run: |
        dir
        pwd

    - name: List directory (working directory)
      working-directory: d:/a/RosegardenW/RosegardenW
      run: |
        dir
        pwd
        
    - name: Qmake and make
      working-directory: d:/a/RosegardenW/RosegardenW
      run: | 
        qmake.exe garderobe.pro -spec win32-g++ "CONFIG+=qtquickcompiler" QMAKE_LIBDIR=${GITHUB_WORKSPACE}/zlib-1.2.3/lib
        mingw32-make.exe qmake_all

    - name: Make mingw32
      working-directory: d:/a/RosegardenW/RosegardenW
      run: mingw32-make.exe -j8

#    - name: Run a multi-line script
#      run: |
#        echo Add other actions to build,
#        echo test, and deploy your project.


