name: CI

on: [push]

- name: Install Qt
  uses: jurplel/install-qt-action@v2.1.0
  with:
    # Directory to install Qt
    dir: # optional
    # Version of Qt to install
    version: # optional, default is 5.12.6
    # Host platform
    host: windows # optional
    # Target platform for build
    target: desktop # optional, default is desktop
    # Architecture for Windows/Android
    arch: win32_mingw53 # optional
    # Whether or not to install Qt dependencies on Linux
    install-deps: # optional, default is true
    
jobs:
  build:

    runs-on: windows

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.

