name: CI

env:
  QT_VERSION:     "5.12.7"
  MINGW_VERSION:  "win32_mingw73"
  MINGW_PATH:     "mingw73_32"
  
on: [push]

jobs:
  build:
    runs-on: windows-latest
    
    steps:
    - name: Uninstall choco versions of mingw
      run: |
        choco uninstall mingw --force
        choco uninstall strawberryperl --force
        
    - uses: numworks/setup-msys2@v1
      with:
        msystem: MINGW32        
        
    - name: Install wget
      run: |
        pip install wget
        pip show wget

    - name: Install zlib
      run: |
        python -m wget https://downloads.sourceforge.net/project/gnuwin32/zlib/1.2.3/zlib-1.2.3-bin.zip -o zlib-1.2.3.zip
        unzip zlib-1.2.3.zip

    - name: Install Qt
      uses: jurplel/install-qt-action@v2
      with:
        version: ${{ env.QT_VERSION }}
        arch:    ${{ env.MINGW_VERSION }}
        extra:   --external 7z

    - uses: actions/checkout@v1
        
    - name: Qmake and make
      working-directory: d:/a/RosegardenW/RosegardenW
      run: | 
        qmake.exe garderobe.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
        mingw32-make.exe qmake_all

    - name: Make mingw32
      working-directory: d:/a/RosegardenW/RosegardenW
      run: mingw32-make.exe -j8


