name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install Qt
      uses: jurplel/install-qt-action@v2.1.0
      with:
        # Directory to install Qt
        #dir: # optional
        # Version of Qt to install
        version: 5.12.6 # optional, default is 5.12.6
        # Host platform
        #host: windows # optional
        # Target platform for build
        target: desktop # optional, default is desktop
        # Architecture for Windows/Android
        arch: win32_mingw73 # optional
        # Whether or not to install Qt dependencies on Linux
        #install-deps: true # optional, default is true

    - uses: actions/checkout@v1

    - name: Qmake
      working-directory: d:/a/RosegardenW/RosegardenW
      run: qmake.exe garderobe.pro -spec win32-g++ "CONFIG+=qtquickcompiler"

#    - name: Run a multi-line script
#      run: |
#        echo Add other actions to build,
#        echo test, and deploy your project.


