name: CI

on: [push]

jobs:
  build:

    runs-on: windows-latest
    steps:
    - name: Install wget
      run: |
        pip install wget
        pip show wget

    - name: Install zlib
      run: |
        python -m wget https://downloads.sourceforge.net/project/gnuwin32/zlib/1.2.3/zlib-1.2.3-bin.zip -o zlib-1.2.3.zip
        unzip zlib-1.2.3.zip

    - name: Install Qt
      uses: jurplel/install-qt-action@v2.1.0
      with:
        # Directory to install Qt
        #dir: # optional
        # Version of Qt to install
        version: 5.12.6 # optional, default is 5.12.6
        # Host platform
        #host: windows # optional
        # Target platform for build
        #target: desktop # optional, default is desktop
        # Architecture for Windows/Android
        arch: win32_mingw73 # optional
        # Whether or not to install Qt dependencies on Linux
        #install-deps: true # optional, default is true
        #modules: core gui xml network widgets printsupport

    - uses: actions/checkout@v1

#    - name: List directory
#      run: |
#        dir
#       pwd

#    - name: List directory (working directory)
#      working-directory: d:/a/RosegardenW/RosegardenW
#      run: |
#        dir
#        pwd
        
    - name: Qmake and make
      working-directory: d:/a/RosegardenW/RosegardenW
      run: | 
        qmake.exe garderobe.pro -spec win32-g++ "CONFIG+=qtquickcompiler"
        mingw32-make.exe qmake_all
# libdirs still causing confusion?
# "QMAKE_LIBDIR+=${GITHUB_WORKSPACE}/zlib-1.2.3/lib"

    - name: Make mingw32
      working-directory: d:/a/RosegardenW/RosegardenW
      run: mingw32-make.exe clean -j8


